# 1.分类

## 朴素贝叶斯

In [1]:
from sklearn.naive_bayes import GaussianNB  

In [2]:
#预测天气   0：晴 1：阴 2：降水 3：多云
data_table = [["date","weather"],
             [1,0],
             [2,1],
             [3,2],
             [4,1],
             [5,2],
             [6,0],
             [7,0],
             [8,3],
             [9,1],
             [10,1]]

In [3]:
# 当天的天气
X = [[0],[1],[2],[1],[2],[0],[0],[3],[1]]

In [5]:
#当天天气对应后一天的天气
y = [1,2,1,2,0,0,3,1,1]

In [6]:
#把训练数据和对应的分类放入分类器中进行训练
clf = GaussianNB().fit(X,y)

In [7]:
p = [[1]]
clf.predict(p)

array([2])

In [8]:
#疾病预测
#基因片段A  基因片段B 高血压胆结石
#1：是  0：否
data_table = [
    [1,1,1,0],
    [0,0,0,1],
    [0,1,0,0],
    [1,0,0,0],
    [1,1,0,1],
    [1,0,0,1],
    [0,1,1,1],
    [0,0,0,0],
    [1,0,1,0],
    [0,1,0,1]
]

In [9]:
#基因片段
X=[[1,1],[0,0],[0,1],[1,0],[1,1],[1,0],[0,1],[0,0],[1,0],[0,1]]

In [10]:
#高血压
y1 = [1,0,0,0,0,0,1,0,1,0]

In [11]:
#训练
clf = GaussianNB().fit(X,y1)

In [12]:
#预测
p = [[1,0]]
clf.predict(p)

array([0])

In [13]:
#胆结石
y2 = [0,1,0,0,1,1,1,0,0,1]

In [14]:
#训练
clf2 = GaussianNB().fit(X,y2)

In [15]:
#预测
p = [[1,0]]
clf2.predict(p)

array([0])

## 决策树

### 信息增益  连续性变量

#### “学历”字段分割：

In [16]:
#学历分类中大专，本科，硕士占比
education = (2.0 / 12 , 5.0 / 12 , 5.0 / 12)
#大专分类中相亲占比
junior_college = (1.0 / 2, 1.0 / 2)
#本科分类中相亲占比
undergraduate = (3.0 / 5, 2.0 / 5)
#硕士分类中相亲占比
master = (4.0 / 5, 1.0 / 5)
#学历各分类中相亲占比
date_per = (junior_college,undergraduate,master)

In [20]:
from math import log

In [21]:
#“相亲”字段划分规则下的熵
def info_date(p):
    info = 0
    for v in p:
        info += v * log(v,2)
    return info

#“学历”字段划分规则下的熵
def infoA():
    info = 0
    for i in range(len(education)):
        info += -education[i] * info_date(date_per[i])
    return info
print (infoA())

0.8720327872258462


#### “年龄”字段分割：

In [22]:
#年龄
age = [25,25,28,28,29,30,33,34,35,36,40,46]
#是否相亲 1：是   0：否
date = [0,1,1,0,1,1,1,1,1,0,0,0]

In [23]:
#从年龄28,29中间分开
#左右分类中的数量占总数的百分比
split_per = (4.0 / 12 ,8.0 / 12)
#左边分类中相亲占比
date_left = (1.0 / 2 , 1.0 / 2)
#右边分类中相亲占比
date_right = (5.0 / 8 , 3.0 / 8)
#左右各分类中相亲占比
date_per = (date_left, date_right)

In [25]:
#"相亲"字段划分规则下的熵
def info_date(p):
    info = 0
    for v in p:
        info += v *log(v,2)
    return info 

In [26]:
#右边分类规则下的熵
def infoA():
    info = 0
    for i in range(len(split_per)):
        info += -split_per[i] * info_date(date_per[i])
    return info
print (infoA())

0.9696226686166431


### 随机森林

In [1]:
from sklearn.ensemble import RandomForestClassifier

In [2]:
#学历 0：大专  2：硕士  1：本科
#‘年龄’ '身高'‘年收入’‘学历’
X = [
    [25,179,15,0],
    [33,190,19,0],
    [28,180,18,2],
    [25,178,18,2],
    [46,100,100,2],
    [40,170,170,1],
    [34,174,20,2],
    [36,181,55,1],
    [35,170,25,3],
    [30,180,35,1],
    [28,174,30,1],
    [29,176,36,1]    
]

In [3]:
#是否有相亲  0：N  1：Y
y = [0,1,1,1,0,0,1,0,1,1,0,1]

In [4]:
#现在把训练数据和对应的分类放入分类器中进行训练
clf = RandomForestClassifier().fit(X,y)

d:\python3.5\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


In [5]:
#预测下面此人是否相亲
p = [[28,180,18,2]]
clf.predict(p)

array([1])

### 隐马尔科夫模型

马尔科夫链：在给定当前知识或信息的情况下，观察对象过去的历史状态对于预测将来是无关的。
下一个状态（第n+1个状态）如何的概率只需要观察和统计当前状态（第n个状态）即可正确得出

隐马尔科夫链是贝叶斯信念网络的一种特例，是一个双重的随机过程。不仅状态转移是一个随机事件，状态和输出之间也是一个随机过程。   可见状态链   隐含状态链   输出概率

【问题1】：知道骰子有几种（隐含状态数量）、每种骰子是什么（转换概率）、根据掷骰子掷出的结果（可见状态链），想知道每次掷出来的都是哪种骰子（隐含状态链）。  解码问题 1.求最大似然状态路径，求一串骰子序列，产生观测结果的概率最大；2.求每次掷出的骰子分别是某种骰子的概率

【问题2】：知道骰子有几种（隐含状态数量）、每种骰子是什么（转换概率）、根据掷骰子掷出的结果（可见状态链），想知道掷出这个结果的概率。

【问题3】：知道骰子有几种（隐含状态数量）、不知道每种骰子是什么（转换概率），观测到很多次掷骰子的结果（可见状态链），想反推出每种每种骰子是什么（转换概率）

#### 维特比算法

找出可能性最大的隐藏序列     CDMA协议

In [7]:
#coding = utf-8
import numpy as np

In [132]:
jin = ['近','斤','今','金','尽']
jin_per = [0.3, 0.2, 0.1, 0.06, 0.03]

jintian = ['天','填','田','甜','添']
jintian_per = [
    [0.001,0.001,0.001,0.001,0.001,],
    [0.001,0.001,0.001,0.001,0.001,],
    [0.990,0.001,0.001,0.001,0.001,],
    [0.002,0.001,0.850,0.001,0.001,],
    [0.001,0.001,0.001,0.001,0.001,]
]

wo = ['我','窝','喔','握','卧']
wo_per = [0.400, 0.150, 0.090, 0.050, 0.030]

women = ['们','门','闷','焖','扪']
women_per = [
    [0.970,0.001,0.003,0.001,0.001,],
    [0.001,0.001,0.001,0.001,0.001,],
    [0.001,0.001,0.001,0.001,0.001,],
    [0.002,0.001,0.001,0.001,0.001,],
    [0.001,0.001,0.001,0.001,0.001,]
]
N = 5

In [133]:
def found_from_oneword(oneword_per):
    index = []
    values = []
    a = np.array(oneword_per)
    for v in np.argsort(a)[::-1][:N]:
        index.append(v)
        values.append(oneword_per[v])
    return index , values

In [134]:
def found_from_twoword(oneword_per,twoword_per):
    last = 0
    for i in range(len(jin_per)):
        current = np.multiply(oneword_per[i],twoword_per[i])
        if i == 0:
            last = current
        else:
            last = np.concatenate((last,current),axis=0)
    index = []
    values = []
    for v in np.argsort(last)[::-1][:N]:
        index.append([v // 5 , v % 5])
        values.append(last[v])
    return index, values

In [135]:
def predict(word):
    if word == 'jin':
        for i in found_from_oneword(jin_per)[0]:
            print (jin[i])
    elif word == 'jintian':
        for i in found_from_twoword(jin_per, jintian_per)[0]:
            print (jin[i[0]] + jintian[i[1]])
    elif word == 'wo':
        for i in found_from_oneword(wo_per)[0]:
            print(wo[i])
    elif word == 'women':
        for i in found_from_twoword(wo_per, women_per)[0]:
            print(wo[i[0]] + women[i[1]])
    elif word == 'jintianwo':
        index1, values1 = found_from_oneword(wo_per)
        index2, values2 = found_from_twoword(jin_per, jintian_per)
        last = np.multiply(values1, values1)
        for i in np.argsort(last)[::-1][:N]:
            print(jin[index2[i][0]], jintian[index2[i][1]], wo[i])
    elif word == 'jintianwomen':
        index1, values1 = found_from_twoword(jin_per, jintian_per)
        index2, values2 = found_from_twoword(wo_per, women_per)
        last = np.multiply(values1, values1)
        for i in np.argsort(last)[::-1][:N]:
            print(jin[index1[i][0]], jintian[index1[i][1]], wo[index2[i][0]],women[index2[i][0]])
    else:
        pass

In [136]:
predict('jintian')

今天
金田
近天
近填
近田


In [137]:
if __name__ == '__mian__':
    predict('jin')
    #近
    #斤
    #今
    #金
    #尽
    predict('jintian')
    #今天
    #金田
    #近天
    #近填
    #近田
    predict('two')
    #近
    #斤
    #今
    #金
    #尽
    predict('women')
    #我们
    #我闷
    #我门
    #我焖
    #我扪
    predict('jintianwo')
    #今天我
    #金田窝
    #近天喔
    #近填握
    #近田卧
    predict('jintianwomen')
    #今天我们
    #金田我闷
    #近田我扪
    #近填我焖
    #近天我门

In [138]:
predict('women')

我们
我闷
我门
我焖
我扪


In [139]:
predict('jintianwomen')

今 天 我 们
金 田 我 们
近 田 我 们
近 填 我 们
近 天 我 们


#### 前向算法

解决问题2

### 支持向量机SVM

Support Vector Machine 可以用来做模式识别、分类或者回归的机器学习。
关键点1：“超平面”是一个抽象概念 
关键点2：过拟问题
关键点3：不纯度问题

核函数（Kernel）构造  线性核函数、多项式核函数、径向基核函数（RBF核函数）、高斯核函数。
核函数目的，只有在当前维度空间的样本是线性不可分的，就一律映射到更高的维度上去，在更高的维度上找到超平面，得到超平面方程。

sklearn库中，SVC所支持的函数包括Linear（线性核函数）、poly（多项式核函数）、rbf（径向基核函数）、sigmoid（神经元激活核函数）、precomputed（自定义核函数），默认使用rbf核函数

In [11]:
from sklearn import svm
#年龄
X = [[34],[33],[32],[31],[30],[30],[25],[23],[22],[18]]
#质量
y = [1,0,1,0,1,1,0,1,0,1]
#现在把训练数据和对应的分类放入分类器中进行训练
#这里使用rbf
clf = svm.SVC(kernel = 'rbf').fit(X,y)

d:\python3.5\lib\site-packages\sklearn\svm\base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


In [23]:
#预测年龄30的人的质量
p = [[33]]
print(clf.predict(p))

[1]


In [7]:
clf1 = svm.SVC(kernel = 'linear').fit(X,y)
p = [[7]]
clf1.predict(p)

array([1])

### 遗传算法

应用：TSP问题（旅行商问题）、九宫问题（八数码问题）、生产调度问题、背包问题（NP问题）
步骤：1.基因编码   2.设计初始群体  3.适应度计算（剪枝） 4.产生下一代

In [10]:
#coding=utf-8
import random
#背包问题
#物品重量价格
X = {
    1:[10,15],
    2:[15,25],
    3:[20,35],
    4:[25,45],
    5:[30,55],
    6:[35,70]
}
#终止界限
FINISHED_LIMIT = 5
#重量界限
WEIGHT_LIMIT = 80
#染色体长度
CHROMOSOME_SIZE = 6
#遴选次数
SELECT_NUMBER = 4

max_last = 0
diff_last = 10000

#收敛条件、判断退出
def is_finished(fitnesses):
    global max_last
    global diff_last
    
    max_current = 0
    for v in fitnesses:
        if v[1] > max_current:
            max_current = v[1]
        diff = max_current - max_last
        if diff < FINISHED_LIMIT and diff_last < FINISHED_LIMIT:
            return True
        else:
            diff_last = diff
            max_last = max_current
            return False
#初始染色体状态
def init():
    chromosome_state1 = '100100'
    chromosome_state2 = '101010'    
    chromosome_state3 = '010101'    
    chromosome_state4 = '101011'    
    chromosome_states = [chromosome_state1,
                       chromosome_state2 ,
                       chromosome_state3,
                       chromosome_state4]  
    return chromosome_states
#计算适应度
def fitness(chromosome_states):
    fitnesses = []
    for chromosome_state in chromosome_states:
        value_sum = 0
        weight_sum = 0
        for i,v in enumerate(chromosome_state):
            if int(v) == 1:
                weight_sum += X[i+1][0]
                value_sum += X[i+1][1]
        fitnesses.append([value_sum,weight_sum])
    return fitnesses
#筛选
def filter(chromosome_states, fitnesses):
    #重量大于80的被淘汰
    index = len(fitnesses) - 1
    while index >= 0:
        index -= 1
        if fitnesses[index][1] > WEIGHT_LIMIT:
            chromosome_states.pop(index)
            fitnesses.pop(index)
    #遴选
    selected_index = [0] * len(chromosome_states)
    for i in range(SELECT_NUMBER):
        j = chromosome_states.index(random.choice(chromosome_states))
        selected_index[j] += 1
    return selected_index
#产生下一代
def crossover(chromosome_states,selected_index):
    chromosome_states_new = []
    index = len(chromosome_states) - 1
    while index >= 0:
        index -= 1
        chromosome_state = chromosome_states.pop(index)
        for i in range(selected_index[index]):
            chromosome_state_x = random.choice(chromosome_states)
            pos = random.choice(range(1,CHROMOSOME_SIZE -1))
            chromosome_states_new.append(chromosome_state[:pos] + chromosome_state_x[pos:])
            chromosome_states.insert(index, chromosome_state)
    return chromosome_states_new

In [11]:
if __name__ == '__main__':
    #初始群体
    chromosome_states = init()
    n = 100
    while n > 0:
        n -= 1
        #适应度计算
        fitnesses = fitness(chromosome_states)
        if is_finished(fitnesses):
            break
        #遴选
        selected_index = filter(chromosome_states,fitnesses)
        #产生下一代
        chromosome_states = crossover(chromosome_states,selected_index)

In [12]:
 chromosome_states

['010101', '010010', '010010', '010010']